# # Configuration file for ENFify - Audio Tampering Detection Tool
# # Same as defaults.yml. If a value is missing or null, the default value will be used.

# Downsampling Configuration
downsample: null
downsampling_freq: null  # Frequency to downsample to in Hz

# Bandpass Filter Configuration
bandpassfilter: null 
bandpass_lowcut: null     # Low cut frequency in Hz
bandpass_highcut: null   # High cut frequency in Hz

# Variational Mode Decomposition (VMD) Configuration
VMD: null
VMD_params: 
  alpha: null            # Balancing parameter of the data-fidelity constraint
  tau: null                 # Noise-tolerance (no strict fidelity enforcement)
  n_mode: null              # Number of modes to be recovered
  DC: null              # True if the first mode is to be DC (0-freq)
  tol: null              # Tolerance of convergence criterion

# Phase Analysis Configuration
expected_enf: null      # Expected ENF frequency in Hz
num_cycles: null        # Number of cycles for phase estimation
n_dft: null             # Number of points in DFT for phase estimation
