# # Configuration file for ENFify - Audio Tampering Detection Tool
# # Same as defaults.yml. If a value is missing or null, the default value will be used.
downsample:
  is_enabled: false
  downsampling_frequency: 400

VMD: 
  is_enabled: false
  alpha: 2000            # Balancing parameter of the data-fidelity constraint
  tau: 0                 # Noise-tolerance (no strict fidelity enforcement)
  n_mode: 1             # Number of modes to be recovered
  DC: false              # True if the first mode is to be DC (0-freq)
  tol: !!float 1e-7              # Tolerance of convergence criterion
